trigger:
  branches:
    include:
      - main  # Runs the pipeline on every push to main

pool:
  name: 'Default'  # Use your self-hosted agent pool

variables:
  ACR_NAME: 'lanceoacr'  # Azure Container Registry name (must be lowercase)
  AKS_CLUSTER: 'aks-cluster'
  RESOURCE_GROUP: 'k8s-resource-group'
  IMAGE_NAME: 'my-app'
  IMAGE_TAG: '$(Build.BuildId)'  # Unique tag for Docker images

steps:
  - checkout: self  # Ensures the latest code is checked out

  - task: PowerShell@2
    displayName: 'Authenticate to Azure and ACR'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "🔐 Logging into Azure..."
        az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)
        Write-Host "🔐 Logging into Azure Container Registry..."
        az acr login --name $(ACR_NAME)

  - task: PowerShell@2
    displayName: 'Build & Push Docker Image'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "🐳 Building Docker image..."
        docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG) .
        Write-Host "🚀 Pushing Docker image to ACR..."
        docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG)

  - task: HelmInstaller@1
    displayName: 'Install Helm'
    inputs:
      helmVersionToInstall: 'latest'

  - task: PowerShell@2
    displayName: 'Deploy to AKS'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "🔑 Getting AKS credentials..."
        az aks get-credentials --resource-group $(RESOURCE_GROUP) --name $(AKS_CLUSTER)
        Write-Host "🚢 Deploying to AKS with Helm..."
        helm upgrade --install my-app ./my-app `
          --set image.repository=$(ACR_NAME).azurecr.io/$(IMAGE_NAME) `
          --set image.tag=$(IMAGE_TAG)

