trigger:
  branches:
    include:
      - main  # Runs the pipeline on every push to main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACR_NAME: 'lanceoacr'  # Your Azure Container Registry name (lowercase)
  AKS_CLUSTER: 'aks-cluster'
  RESOURCE_GROUP: 'k8s-resource-group'
  IMAGE_NAME: 'my-app'

steps:
  - script: |
      az login --identity || az login --use-device-code
      az acr login --name $(ACR_NAME)
    displayName: 'Authenticate to Azure and ACR'

  - script: |
      docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId) .
      docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId)
    displayName: 'Build & Push Docker Image'

  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: 'latest'

  - script: |
      az aks get-credentials --resource-group $(RESOURCE_GROUP) --name $(AKS_CLUSTER)
      helm upgrade --install my-app ./my-app --set image.repository=$(ACR_NAME).azurecr.io/$(IMAGE_NAME) --set image.tag=$(Build.BuildId)
    displayName: 'Deploy to AKS'

