trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'  # Your self-hosted or Microsoft-hosted agent

variables:
  ACR_NAME: 'lanceoacr'
  AKS_CLUSTER: 'aks-cluster'
  RESOURCE_GROUP: 'k8s-resource-group'
  IMAGE_NAME: 'my-app'
  IMAGE_TAG: '$(Build.BuildId)'

steps:
  - checkout: self

  - task: PowerShell@2
    displayName: 'Authenticate to Azure + ACR'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "🔐 Logging into Azure using System-Assigned Identity..."
        try {
          az login --identity --username 25a98eeb-6aec-406f-95e5-f3710e7d5cda
          Write-Host "✅ Logged into Azure."
        } catch {
          Write-Host "❌ Azure login failed"
          exit 1
        }

        Write-Host "🔐 Logging into Azure Container Registry..."
        try {
          az acr login --name $(ACR_NAME)
          Write-Host "✅ Logged into ACR."
        } catch {
          Write-Host "❌ ACR login failed"
          exit 1
        }

  - task: PowerShell@2
    displayName: 'Build & Push Docker Image'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "🐳 Building Docker image..."
        docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG) .

        Write-Host "🚀 Pushing Docker image to ACR..."
        docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG)

  - task: HelmInstaller@1
    displayName: 'Install Helm'
    inputs:
      helmVersionToInstall: 'latest'

  - task: PowerShell@2
    displayName: 'Deploy to AKS via Helm'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "🔑 Fetching AKS credentials..."
        az aks get-credentials --resource-group $(RESOURCE_GROUP) --name $(AKS_CLUSTER)

        Write-Host "🚢 Deploying Helm chart..."
        helm upgrade --install my-app ./my-app `
          --set image.repository=$(ACR_NAME).azurecr.io/$(IMAGE_NAME) `
          --set image.tag=$(IMAGE_TAG)

