trigger:
  branches:
    include:
      - main

# 👇 Use your self-hosted agent pool (named "Default" by default)
pool:
  name: 'Default'

variables:
  ACR_NAME: 'julienfacr'
  AKS_CLUSTER: 'aks-cluster'
  RESOURCE_GROUP: 'k8s-resource-group'
  IMAGE_NAME: 'my-app'
  IMAGE_TAG: '$(Build.BuildId)'
  AZURE_CONNECTION: 'Azure-Julien-ServiceConnection'   # Azure Resource Manager
  ACR_CONNECTION: 'JulienACRConnection'                # Docker Registry

steps:
- checkout: self

# ✅ Login to Azure (optional but good for clarity)
- task: AzureCLI@2
  displayName: 'Login to Azure'
  inputs:
    azureSubscription: '$(AZURE_CONNECTION)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "🔐 Logging into Azure..."
      az acr login --name $ACR_NAME

# 🐳 Build and Push Docker Image
- task: Docker@2
  displayName: 'Build and Push Docker Image to ACR'
  inputs:
    containerRegistry: '$(ACR_CONNECTION)'
    repository: '$(IMAGE_NAME)'
    command: 'buildAndPush'
    Dockerfile: 'my-app/Dockerfile'
    tags: |
      $(IMAGE_TAG)

# 🛠 Install Helm
- task: HelmInstaller@1
  displayName: 'Install Helm'
  inputs:
    helmVersionToInstall: 'latest'

# 🚀 Deploy to AKS using Helm
- task: AzureCLI@2
  displayName: 'Deploy to AKS with Helm'
  inputs:
    azureSubscription: '$(AZURE_CONNECTION)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "🔑 Getting AKS credentials..."
      az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER --overwrite-existing

      echo "🚢 Deploying with Helm..."
      helm upgrade --install my-app ./my-app \
        --set image.repository=$ACR_NAME.azurecr.io/$IMAGE_NAME \
        --set image.tag=$IMAGE_TAG

