apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
spec:
  provider: azure
  secretObjects:
    - secretName: my-secret
      type: Opaque
      data:
        - objectName: MY-SECRET
          key: password
  parameters:
    usePodIdentity: "false"
    keyvaultName: "JulienFmyVault"
    objects: |
      array:
        - |
          objectName: MY-SECRET
          objectType: secret
    tenantId: 06819877-2ba4-408c-8f50-1bff6612b2da

