# Number of replicas (pods) running the app
replicaCount: 2

# Container image details
image:
  repository: julienfacr.azurecr.io/my-app  # ✅ Updated to your ACR image
  tag: "5"                                   # ✅ Match the tag built in pipeline
  pullPolicy: IfNotPresent

# Kubernetes service configuration
service:
  type: LoadBalancer  # ✅ Keeps it publicly accessible
  port: 5000          # ✅ Matches Flask app port

# Service account configuration
serviceAccount:
  create: true
  name: ""

# Environment variables (optional — you can add later if needed)
env: []

# Ingress (Disabled for now, but can be enabled later)
ingress:
  enabled: false

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Autoscaling (can be enabled later)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

# Node scheduling
nodeSelector: {}
tolerations: []
affinity: {}

