# Number of replicas (pods) running the app
replicaCount: 2

# Container image details
image:
  repository: nginx  # Change this to your own Docker image (e.g., mydockerhub/myapp)
  tag: latest
  pullPolicy: IfNotPresent

# Kubernetes service configuration
service:
  type: LoadBalancer  # Exposes the app externally with a public IP
  port: 80

# Service account configuration
serviceAccount:
  create: true  # Ensure service account is created to avoid Helm error
  name: ""

# Environment variables - Uses Kubernetes Secret for DB_PASSWORD
env:
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: my-secret  # The Kubernetes Secret name
        key: dbPassword  # The key inside the Secret

# Ingress (Disabled for now, but can be enabled later)
ingress:
  enabled: false

# Resource limits (optional, but recommended for production)
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Autoscaling (Disabled for now, we will enable later)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

# Node Affinity (For advanced scheduling, leaving it empty for now)
nodeSelector: {}
tolerations: []
affinity: {}

